name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Angular
        run: npm run build -- --configuration production --base-href=/${{ github.event.repository.name }}/

      - name: Debug dist (QUAN TRỌNG)
        run: ls -R dist

      - name: Copy index to 404
        run: cp dist/market-app-vinapulse/browser/index.html dist/market-app-vinapulse/browser/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action
        with:
          branch: gh-pages
          folder: dist/market-app-vinapulse/browser/
          clean: true